# Generated by Django 6.0.4 on 2026-05-15 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='Appareil (ex: iPhone 13)')),
                ('imei_serial', models.CharField(blank=True, max_length=100, verbose_name='IMEI / N° de Série')),
                ('problem_description', models.TextField(verbose_name='Problème signalé')),
                ('technician_notes', models.TextField(blank=True, verbose_name='Notes du technicien')),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('diagnostic', 'Diagnostic en cours'), ('repairing', 'Réparation en cours'), ('ready', 'Prêt / Terminé'), ('delivered', 'Livré au client'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('estimated_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Coût estimé (FCFA)')),
                ('actual_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Coût réel (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison réelle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='clients.client', verbose_name='Client')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
            ],
            options={
                'verbose_name': 'Réparation',
                'verbose_name_plural': 'Réparations',
                'ordering': ['-created_at'],
            },
        ),
    ]
