# Generated by Django 6.0.4 on 2026-05-15 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='N° Facture')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Sous-total (FCFA)')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Remise (FCFA)')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Total (FCFA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('mixte', 'Paiement Mixte')], default='cash', max_length=15, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('completed', 'Terminée'), ('partial', 'Partiellement Payée'), ('pending', 'En Attente'), ('cancelled', 'Annulée')], default='completed', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='clients.client', verbose_name='Client')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque')], default='cash', max_length=15, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence (N° transaction)')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reçu par')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix unitaire (FCFA)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('warranty_months', models.PositiveIntegerField(default=6, verbose_name='Garantie (mois)')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Produit')),
                ('product_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productunit', verbose_name='Unité (IMEI/Série)')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Article de Vente',
                'verbose_name_plural': 'Articles de Vente',
            },
        ),
    ]
