# Generated by Django 6.0.4 on 2026-05-21 02:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('echange', 'Échange / Reprise')], default='cash', max_length=15, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('wave', 'Wave'), ('orange_money', 'Orange Money'), ('virement', 'Virement Bancaire'), ('cheque', 'Chèque'), ('echange', 'Échange / Reprise'), ('mixte', 'Paiement Mixte')], default='cash', max_length=15, verbose_name='Mode de paiement'),
        ),
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ouverture")),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('initial_cash', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Fond de caisse initial (FCFA)')),
                ('cash_sales', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Ventes en espèces (FCFA)')),
                ('expenses_paid', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Dépenses en espèces (FCFA)')),
                ('expected_cash', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Espèces attendues (FCFA)')),
                ('actual_cash', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Espèces réelles déclarées (FCFA)')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('closed', 'Fermée')], default='open', max_length=10, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Fermé par')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Ouvert par')),
            ],
            options={
                'verbose_name': 'Session de Caisse',
                'verbose_name_plural': 'Sessions de Caisse',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('category', models.CharField(choices=[('rent', 'Loyer'), ('transport', 'Transport'), ('salary', 'Salaire'), ('bills', 'Factures (Électricité, Internet, etc.)'), ('other', 'Autre charge')], default='other', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
