# Generated by Django 6.0.4 on 2026-05-15 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('brand', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('xiaomi', 'Xiaomi'), ('oppo', 'OPPO'), ('tecno', 'Tecno'), ('infinix', 'Infinix'), ('itel', 'Itel'), ('google', 'Google'), ('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('asus', 'ASUS'), ('autre', 'Autre')], max_length=20, verbose_name='Marque')),
                ('category', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablette', 'Tablette'), ('laptop', 'Laptop'), ('desktop', 'Ordinateur de Bureau'), ('montre', 'Montre Connectée'), ('ecouteur', 'Écouteurs / AirPods'), ('accessoire', 'Accessoire'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('purchase_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Prix d'achat (FCFA)")),
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente (FCFA)')),
                ('alert_threshold', models.PositiveIntegerField(default=2, verbose_name="Seuil d'alerte stock")),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_serial', models.CharField(max_length=50, unique=True, verbose_name='IMEI / N° de Série')),
                ('condition', models.CharField(choices=[('neuf', 'Neuf'), ('reconditionne', 'Reconditionné'), ('occasion', 'Occasion')], default='neuf', max_length=15, verbose_name='État')),
                ('status', models.CharField(choices=[('in_stock', 'En Stock'), ('sold', 'Vendu'), ('reserved', 'Réservé'), ('returned', 'Retourné'), ('defective', 'Défectueux')], default='in_stock', max_length=15, verbose_name='Statut')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Couleur')),
                ('storage', models.CharField(blank=True, max_length=20, verbose_name='Stockage')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name="Prix d'achat unitaire (FCFA)")),
                ('selling_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix de vente unitaire (FCFA)')),
                ('warranty_months', models.PositiveIntegerField(default=6, verbose_name='Garantie (mois)')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.product')),
            ],
            options={
                'verbose_name': 'Unité Produit',
                'verbose_name_plural': 'Unités Produit',
                'ordering': ['-added_at'],
            },
        ),
    ]
